//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVC.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Required Field")]
        public string FNAME { get; set; }
        [Required(ErrorMessage = "Required Field")]
        [EmailAddress]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Required Field")]
        [MinLength(11,ErrorMessage ="Minimum should be 11 digits")]
        public string MOBILE { get; set; }

        
        public string DESCRIPTION { get; set; }
    }
}
